-- USERS
CREATE TABLE USERS (
    ID NUMBER(19) PRIMARY KEY,
    FULL_NAME VARCHAR2(100) NOT NULL,
    USER_CODE VARCHAR2(36) NOT NULL,
    EMAIL VARCHAR2(255) UNIQUE NOT NULL,
    IS_ACTIVE NUMBER(1) DEFAULT 1,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE SEQUENCE USERS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
ALTER TABLE USERS ADD CONSTRAINT UK_USERS_USER_CODE UNIQUE (USER_CODE);

-- WALLETS
CREATE TABLE WALLETS (
    ID NUMBER(19) PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL,
    CODE VARCHAR2(50) UNIQUE NOT NULL,
    TOTAL_AMOUNT NUMBER(12,4) NOT NULL,
    IS_ACTIVE NUMBER(1) DEFAULT 1,
    USER_ID NUMBER(19) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
);
CREATE SEQUENCE WALLETS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE INDEX IDX_WALLETS_USER_ID ON WALLETS (USER_ID);

-- WALLETS_HISTORY
CREATE TABLE WALLETS_HISTORY (
    ID NUMBER(19) PRIMARY KEY,
    AMOUNT NUMBER(12,4) NOT NULL,
    TRANSACTION_TYPE VARCHAR2(1) CHECK (TRANSACTION_TYPE IN ('C', 'D')) NOT NULL,
    OPERATION_TYPE VARCHAR2(20) NOT NULL, -- Ex: 'DEPOSITO', 'TRANSFERENCIA', 'SAQUE', 'ESTORNO', etc.
    WALLET_ID NUMBER(19) NOT NULL,
    SOURCE_WALLET_ID NUMBER(19), -- Carteira de origem (usado em transferências, pode ser NULL para depósito/saque)
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FOREIGN KEY (WALLET_ID) REFERENCES WALLETS(ID)
);
CREATE SEQUENCE WALLETS_HISTORY_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE INDEX IDX_WALLETS_HISTORY_WALLET_ID ON WALLETS_HISTORY (WALLET_ID);
