-- WALLETS
CREATE TABLE WALLETS (
    ID NUMBER(19) PRIMARY KEY,
    USER_NAME VARCHAR2(100) NOT NULL,
    NAME VARCHAR2(100) UNIQUE NOT NULL,
    CODE VARCHAR2(50) UNIQUE NOT NULL,
    TOTAL_AMOUNT NUMBER(12,4) NOT NULL,
    IS_ACTIVE NUMBER(1) DEFAULT 1,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE SEQUENCE WALLETS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE INDEX IDX_WALLETS_USER_NAME ON WALLETS (USER_NAME);

-- WALLETS_HISTORY
CREATE TABLE WALLETS_HISTORY (
    ID NUMBER(19) PRIMARY KEY,
    AMOUNT NUMBER(12,4) NOT NULL,
    TRANSACTION_TYPE VARCHAR2(1) NOT NULL,
    OPERATION_TYPE VARCHAR2(20) NOT NULL, -- Ex: 'DEPOSITO', 'TRANSFERENCIA', 'SAQUE', 'ESTORNO', etc.
    OPERATION_STATUS VARCHAR2(20) NOT NULL, -- Ex: 'CREATED', 'PROCESSING', 'ERROR', 'CANCELED', etc.
    WALLET_ID NUMBER(19) NOT NULL,
    SOURCE_WALLET_ID NUMBER(19), -- Carteira de origem (usado em transferências, pode ser NULL para depósito/saque)
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FOREIGN KEY (WALLET_ID) REFERENCES WALLETS(ID)
);
CREATE SEQUENCE WALLETS_HISTORY_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE INDEX IDX_WALLETS_HISTORY_WALLET_ID ON WALLETS_HISTORY (WALLET_ID);
