spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/ORCLPDB1.localdomain
    username: WALLET_ASSIGNMENT_ADM
    password: 123
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: false

  flyway:
    enabled: false

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: TRACE


