ALTER SESSION SET CONTAINER = ORCLPDB1;

CREATE TABLESPACE TSI_WALLET_ASSIGNMENT_01
    DATAFILE '/opt/oracle/oradata/ORCLCDB/ORCLPDB1/TSI_WALLET_ASSIGNMENT_01.dbf'
    SIZE 50M AUTOEXTEND ON NEXT 50M MAXSIZE UNLIMITED;

CREATE TABLESPACE TSD_WALLET_ASSIGNMENT_01
    DATAFILE '/opt/oracle/oradata/ORCLCDB/ORCLPDB1/TSD_WALLET_ASSIGNMENT_01.dbf'
    SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED;

CREATE USER WALLET_ASSIGNMENT_ADM IDENTIFIED BY 123
    DEFAULT TABLESPACE TSD_WALLET_ASSIGNMENT_01
    QUOTA UNLIMITED ON TSD_WALLET_ASSIGNMENT_01
    ACCOUNT UNLOCK;

GRANT ALL PRIVILEGES TO WALLET_ASSIGNMENT_ADM;
GRANT UNLIMITED TABLESPACE TO WALLET_ASSIGNMENT_ADM;

GRANT EXECUTE ON SYS.DBMS_REDACT TO WALLET_ASSIGNMENT_ADM;
GRANT EXEMPT REDACTION POLICY TO WALLET_ASSIGNMENT_ADM;

ALTER SESSION SET CURRENT_SCHEMA = WALLET_ASSIGNMENT_ADM;
